### ISSUE TITLE
Unable to run docker-compose up

### ISSUE THREAD

**Issue by NimzyMaina** [UsamaAshraf/microservices-using-rabbitmq#1]
When building the image I get the following error. Kindly assist.

```bash
Reading package lists...
+ + grep -q Package: erlang-base-hipe
apt-cache show erlang-base-hipe
+ apt-get install -y --no-install-recommends erlang-base-hipe
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 erlang-base-hipe : Depends: libtinfo6 (>= 6) but it is not installable
E: Unable to correct problems, you have held broken packages.
ERROR: Service 'rabbitmq-server' failed to build: The command '/bin/sh -c set -eux;     apt-get update;  if apt-cache show erlang-base-hipe 2>/dev/null | grep -q 'Package: erlang-base-hipe'; then             apt-get install -y --no-install-recommends                      erlang-base-hipe                ;       fi;     apt-get install -y --no-install-recommends              erlang-asn1             erlang-crypto           erlang-eldap            erlang-inets            erlang-mnesia           erlang-nox              erlang-os-mon           erlang-public-key               erlang-ssl
erlang-xmerl    ;       rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
```

Kind regards

**Comment by masonlr** [comment]
@NimzyMaina the detail of the RabbitMQ `Dockerfile` is not so important for the tutorial. As a workaround, you could modify the `docker-compose.yml` file to pull `rabbitmq:latest` directly from Docker Hub, i.e.:

```yaml
version: "3.2"
services:
    rabbitmq-server:
        image: rabbitmq:latest

    python-service:
        build: ./python-service
        # 'rabbitmq-server' will be available as a network reference inside this service 
        # and this service will start only after the RabbitMQ service has.
        depends_on:
            - rabbitmq-server
        # Keep it running.  
        tty: true
        # Map port 3000 on the host machine to port 3000 of the container.
        ports:
            - "3000:3000"
        volumes:
            - './python-service:/python-service'

    go-service:
        build: ./go-service
        depends_on:
            - rabbitmq-server
        tty: true
        volumes:
            - './go-service:/go-service'

# Host volumes used to store code.
volumes:
    python-service:
    go-service:

```
